// Generated by CoffeeScript 1.6.3
(function() {
  define({
    properties: {
      some_property: 111
    },
    application: {
      view: {
        el: "#main"
      },
      router: {
        routes: {}
      }
    }
  });

}).call(this);
