// Generated by CoffeeScript 1.6.3
(function() {
  define({
    index: {
      path: "src/modules/module/index",
      regions: {
        ".main": "hello"
      }
    },
    hello: {
      path: "src/modules/module/index"
    }
  });

}).call(this);
