// Generated by CoffeeScript 1.6.3
(function() {
  define({
    index: {
      key: "index",
      path: "src/modules/module/index",
      options: {},
      regions: {
        ".main": "hello"
      }
    },
    hello: {
      key: "hello",
      path: "src/modules/module/index",
      options: {}
    }
  });

}).call(this);
