// Generated by CoffeeScript 1.6.3
(function() {
  define({
    event_dispatcher: {
      path: "app/classes/base/event-dispatcher",
      deps: {
        "arguments": [
          {
            test: 123
          }
        ]
      }
    },
    index: {
      path: "src/modules/index/index",
      deps: {
        "arguments": [
          {
            id: "index_module",
            dispatcher: "@event_dispatcher",
            route: "index",
            regions: {
              ".main": "@hello"
            }
          }
        ]
      }
    },
    hello: {
      path: "src/modules/hello/hello",
      deps: {
        "arguments": [
          {
            id: "hello",
            route: "index/hello",
            regions: {
              ".sub": "@hello1"
            },
            dispatcher: "@event_dispatcher"
          }
        ]
      }
    },
    hello1: {
      path: "src/modules/hello1/hello1",
      deps: {
        "arguments": [
          {
            id: "hello1",
            route: "index/hello/hello1",
            dispatcher: "@event_dispatcher"
          }
        ]
      }
    }
  });

}).call(this);

/*
//@ sourceMappingURL=layouts.map
*/
