// Generated by CoffeeScript 1.6.3
(function() {
  define(["app/classes/abstract/dm", "src/config/layouts"], function(dm, layouts) {
    return {
      properties: {
        test: 1234
      },
      services: {
        "module-manager": {
          path: "app/services/module-manager/module-manager",
          deps: {
            calls: {
              setConfig: [dm.escape(layouts)]
            }
          }
        },
        "bus": {
          path: "app/services/bus/bus"
        }
      }
    };
  });

}).call(this);

/*
//@ sourceMappingURL=services.map
*/
