// Generated by CoffeeScript 1.6.3
(function() {
  define(["app/config/layouts"], function(layouts) {
    return {
      "module-manager": {
        path: "app/services/module-manager",
        options: {},
        deps: {
          calls: {
            setConfig: [layouts]
          }
        }
      }
    };
  });

}).call(this);
